#spring.application.name=Outil-service
#spring.config.import=configserver:http://localhost:8881
spring.application.name=Outil-service

# utiliser le config server déployé
spring.cloud.config.uri=https://radiant-intuition-production.up.railway.app
spring.cloud.config.enabled=true
spring.config.import=optional:

# eureka déployé
eureka.client.service-url.defaultZone=https://registeryservice-production.up.railway.app/eureka/

# port dynamique Railway
server.port=${PORT:8080}
